version: '3'
services:
  postgres:
    container_name: reactui_postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env
    networks:
      - reactui

  pgadmin:
    container_name: reactui_pgadmin
    links:
      - postgres:postgres
    image: dpage/pgadmin4:latest
    ports:
      - '8080:80'
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env
    networks:
      - reactui

networks:
  reactui:
    driver: bridge
